# Generated by Django 4.1.5 on 2023-01-09 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_id_window_tickets_window_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windows',
            name='operator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
    ]
