# Generated by Django 4.1.5 on 2023-01-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_windows_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='service',
            field=models.CharField(max_length=50, null=True, verbose_name='Услуга'),
        ),
    ]
