# Generated by Django 4.1.5 on 2023-01-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tickets_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='id_services',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID набора сервисов'),
        ),
    ]
