# Generated by Django 4.1.5 on 2023-01-30 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logwindows',
            name='time_pause',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Время пауз'),
        ),
    ]
